name: Run R Scripts

on: 
  push:
  #schedule: 
  #  - cron: '0 * * * *'

jobs:
  render:
    name: Run R script
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v4
      - uses: r-lib/actions/setup-pandoc@v4
      - name: Run toenail R script
        run: Rscript 04-toenail.R
